#!/usr/bin/env python
bearer_token: 'AAAAAAAAAAAAAAAAAAAAACfqdAEAAAAAT%2B5yEJ%2FUTMSFJ4KEfvjl3Y7qkl8%3D1EA3ivv8BryoaKk9vLYM6HTZ1dLUUJSpfG4kiKbsEzwuIy4s54'
project_id: 'sound-splicer-351114'
topic_name: 'twitter_topic'
hashtag: ['#macron']