name: Docker Image CI

on:
  push:
    branches: 
    - 'main'
    - 'add_use_case'
  pull_request:
    branches: 
    - 'main'
    - 'add_use_case'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          
    -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
    -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./Level_1/Test_model/
          file: ./Level_1/Test_model/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/gcp-project-test-model:latest
          
    -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./Level_1/Preprocess/
          file: ./Level_1/Preprocess/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/gcp-project-preprocess:latest
    -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./Level_1/trainer/
          file: ./Level_1/trainer/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/gcp-project-trainer:latest
          
   
        

